version: '3.6'
services:
    config-api:
        image: 'node:11-stretch'
        volumes:
            - './:/app'
        working_dir: '/app'
        command: ['sh', '-c', 'npm install && node dev/files.js']
        networks:
            - okty-api
    lambda-api:
        image: 'node:11-stretch'
        volumes:
            - './:/app'
        working_dir: '/app'
        command: ['sh', '-c', 'npm install && node dev/lambda.js']
        networks:
            - okty-api

networks:
    okty-api:
        name: okty-api